services:
  snakeaid-api:
    image: thekhiem7/snakeaid-api:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080

      # Settings for container 
      - ASPNETCORE_HTTPS_PORT=
      - ASPNETCORE_Kestrel__Certificates__Default__Path=
      - DOTNET_RUNNING_IN_CONTAINER=true

    restart: unless-stopped